### ISSUE TITLE
ValueError: Shapes (768, 768) and (768, 12, 64) are incompatible

### ISSUE THREAD

**Issue by lfoppiano** [CederGroupHub/MatEntityRecognition#24]
I'm trying to get to use this Material Entity Recognition and I'm having a problem when I try to load the model. 

It seems that shapes within the model are not compatible, as the error message suggests: `ValueError: Shapes (768, 768) and (768, 12, 64) are incompatible`

See the full log: 

```
>>> from materials_entity_recognition import MatRecognition  
>>> model = MatRecognition()  
2021-06-04 12:09:36.035092: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
lr_method_name, lr_method_parameters adamdecay {'lr': 1e-05, 'epsilon': 1e-08, 'warmup': 0.1}
num_train_steps, num_warmup_steps 250000 25000
classifier_type lstm
2021-06-04 12:09:36.290432: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
WARNING:tensorflow:From /Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lfoppiano/development/github/MatEntityRecognition/materials_entity_recognition/scripts/mat_models.py", line 641, in __init__
    self.model = NERModel.reload_model(model_path=self.model_path, bert_path=self.bert_path)
  File "/Users/lfoppiano/development/github/MatEntityRecognition/materials_entity_recognition/scripts/model_framework.py", line 953, in reload_model
    model.load_weights(cp_path)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2297, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1339, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 258, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 972, in _restore_from_checkpoint_position
    visit_queue=visit_queue))
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 1007, in _single_restoration_from_checkpoint_position
    if child_position.bind_object(trackable=local_object):
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 312, in bind_object
    slot_name=slot_restoration.slot_name)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 1397, in _create_or_restore_slot_variable
    slot_variable_position.restore(slot_variable)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 258, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 978, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 309, in restore_saveables
    validated_saveables).restore(self.save_path_tensor, self.options)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 339, in restore
    restore_ops = restore_fn()
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 323, in restore_fn
    restore_ops.update(saver.restore(file_prefix, options))
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 116, in restore
    restored_tensors, restored_shapes=None)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 132, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 308, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/Users/lfoppiano/opt/anaconda3/envs/MatEntityRecognition/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1161, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (768, 768) and (768, 12, 64) are incompatible
```

I've created a conda environment with python 3.7 and installed the packages as following the requirements.txt: 

```
(MatEntityRecognition) lucas-mbp:MatEntityRecognition lfoppiano$  pip list
Package                 Version
----------------------- -------------------
absl-py                 0.12.0
appdirs                 1.4.4
astunparse              1.6.3
beautifulsoup4          4.9.3
blis                    0.7.4
cached-property         1.5.2
cachetools              4.2.2
catalogue               2.0.4
certifi                 2021.5.30
cffi                    1.14.5
chardet                 4.0.0
ChemDataExtractor       1.3.0
click                   7.1.2
cryptography            3.4.7
cssselect               1.1.0
cymem                   2.0.5
DAWG                    0.8.0
en-core-web-sm          3.0.0
filelock                3.0.12
flatbuffers             1.12
gast                    0.4.0
google-auth             1.30.1
google-auth-oauthlib    0.4.4
google-pasta            0.2.0
grpcio                  1.34.1
h5py                    3.1.0
huggingface-hub         0.0.8
idna                    2.10
importlib-metadata      4.5.0
Jinja2                  3.0.1
joblib                  1.0.1
keras-nightly           2.5.0.dev2021032900
Keras-Preprocessing     1.1.2
lxml                    4.6.3
Markdown                3.3.4
MarkupSafe              2.0.1
murmurhash              1.0.5
nltk                    3.6.2
numpy                   1.19.5
oauthlib                3.1.1
opt-einsum              3.3.0
packaging               20.9
pathy                   0.5.2
pdfminer.six            20201018
pip                     21.1.1
preshed                 3.0.5
protobuf                3.17.2
psutil                  5.8.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycparser               2.20
pydantic                1.7.4
pyparsing               2.4.7
python-crfsuite         0.9.7
python-dateutil         2.8.1
PyYAML                  5.4.1
regex                   2021.4.4
requests                2.25.1
requests-oauthlib       1.3.0
rsa                     4.7.2
sacremoses              0.0.45
setuptools              52.0.0.post20210125
six                     1.15.0
smart-open              3.0.0
sortedcontainers        2.4.0
soupsieve               2.2.1
spacy                   3.0.6
spacy-legacy            3.0.5
srsly                   2.4.1
tensorboard             2.5.0
tensorboard-data-server 0.6.1
tensorboard-plugin-wit  1.8.0
tensorflow              2.5.0
tensorflow-addons       0.13.0
tensorflow-estimator    2.5.0
termcolor               1.1.0
thinc                   8.0.3
tokenizers              0.10.3
torch                   1.8.1
tqdm                    4.61.0
transformers            4.6.1
typeguard               2.12.0
typer                   0.3.2
typing-extensions       3.7.4.3
urllib3                 1.26.5
wasabi                  0.8.2
Werkzeug                2.0.1
wheel                   0.36.2
wrapt                   1.12.1
zipp                    3.4.1

(MatEntityRecognition) lucas-mbp:MatEntityRecognition lfoppiano$ python --version
Python 3.7.10

```

**Comment by muthuku** [comment]
I am having this same problem did you or anyone else figure this out?

**Comment by zhugeyicixin** [comment]
Thanks for reaching out! That's probably because you didn't download the model. If you have gif lfs, the model would be downloaded automatically. Could you try to download git lfs first and then use git lfs pull to download the model? That should address the problem. Please feel free to follow up if you have further questions. @lfoppiano @muthuku

**Comment by muthuku** [comment]
I uninstalled the package and downloaded git lfs. Do I still git clone git@github.com:CederGroupHub/MatEntityRecognition.git or git lfs clone the repo? And when you say git lfs pull what are we pulling, the repo? I am an college intern working on a project and I am not too familiar with how to download and utilize things from github. Thank you for your help

**Comment by muthuku** [comment]
Hi I tried git lfs clone of the MatEntityRecognition which cloned the larger this larger file around 1.6 GB which I assume is the model, but I still got the same error. Did I do something wrong or is there something else I could try?:

`2021-06-24 17:12:45.242336: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
lr_method_name, lr_method_parameters adamdecay {'lr': 1e-05, 'epsilon': 1e-08, 'warmup': 0.1}
num_train_steps, num_warmup_steps 250000 25000
classifier_type lstm
2021-06-24 17:12:46.359474: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2)
WARNING:tensorflow:From /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version.
Instructions for updating:
The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU.
WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss.
WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/mat_models.py", line 641, in __init__
    self.model = NERModel.reload_model(model_path=self.model_path, bert_path=self.bert_path)
  File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/model_framework.py", line 953, in reload_model
    model.load_weights(cp_path)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2297, in load_weights
    status = self._trackable_saver.restore(filepath, options)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1339, in restore
    checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 258, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 972, in _restore_from_checkpoint_position
    visit_queue=visit_queue))
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 1007, in _single_restoration_from_checkpoint_position
    if child_position.bind_object(trackable=local_object):
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 312, in bind_object
    slot_name=slot_restoration.slot_name)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 1397, in _create_or_restore_slot_variable
    slot_variable_position.restore(slot_variable)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 258, in restore
    restore_ops = trackable._restore_from_checkpoint_position(self)  # pylint: disable=protected-access
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 978, in _restore_from_checkpoint_position
    tensor_saveables, python_saveables))
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 309, in restore_saveables
    validated_saveables).restore(self.save_path_tensor, self.options)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 339, in restore
    restore_ops = restore_fn()
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 323, in restore_fn
    restore_ops.update(saver.restore(file_prefix, options))
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 116, in restore
    restored_tensors, restored_shapes=None)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 132, in restore
    self.handle_op, self._var_shape, restored_tensor)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 308, in shape_safe_assign_variable_handle
    shape.assert_is_compatible_with(value_tensor.shape)
  File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1161, in assert_is_compatible_with
    raise ValueError("Shapes %s and %s are incompatible" % (self, other))
ValueError: Shapes (768, 768) and (768, 12, 64) are incompatible`

**Comment by zhugeyicixin** [comment]
> I uninstalled the package and downloaded git lfs. Do I still git clone [git@github.com](mailto:git@github.com):CederGroupHub/MatEntityRecognition.git or git lfs clone the repo? And when you say git lfs pull what are we pulling, the repo? I am an college intern working on a project and I am not too familiar with how to download and utilize things from github. Thank you for your help

Git lfs pull is used to pull the model files because they are large. If git lfs is installed successfully, then using "git clone repo_url" would download the model files automatically. Otherwise, you could you git lfs pull to do it explicitly.

**Comment by zhugeyicixin** [comment]
> Hi I tried git lfs clone of the MatEntityRecognition which cloned the larger this larger file around 1.6 GB which I assume is the model, but I still got the same error. Did I do something wrong or is there something else I could try?:
> 
> `2021-06-24 17:12:45.242336: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. lr_method_name, lr_method_parameters adamdecay {'lr': 1e-05, 'epsilon': 1e-08, 'warmup': 0.1} num_train_steps, num_warmup_steps 250000 25000 classifier_type lstm 2021-06-24 17:12:46.359474: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2) WARNING:tensorflow:From /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version. Instructions for updating: The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU. WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss. WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss. Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/mat_models.py", line 641, in __init__ self.model = NERModel.reload_model(model_path=self.model_path, bert_path=self.bert_path) File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/model_framework.py", line 953, in reload_model model.load_weights(cp_path) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2297, in load_weights status = self._trackable_saver.restore(filepath, options) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1339, in restore checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 258, in restore restore_ops = trackable._restore_from_checkpoint_position(self) # pylint: disable=protected-access File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 972, in _restore_from_checkpoint_position visit_queue=visit_queue)) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 1007, in _single_restoration_from_checkpoint_position if child_position.bind_object(trackable=local_object): File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 312, in bind_object slot_name=slot_restoration.slot_name) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 1397, in _create_or_restore_slot_variable slot_variable_position.restore(slot_variable) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 258, in restore restore_ops = trackable._restore_from_checkpoint_position(self) # pylint: disable=protected-access File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 978, in _restore_from_checkpoint_position tensor_saveables, python_saveables)) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 309, in restore_saveables validated_saveables).restore(self.save_path_tensor, self.options) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 339, in restore restore_ops = restore_fn() File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 323, in restore_fn restore_ops.update(saver.restore(file_prefix, options)) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 116, in restore restored_tensors, restored_shapes=None) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 132, in restore self.handle_op, self._var_shape, restored_tensor) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 308, in shape_safe_assign_variable_handle shape.assert_is_compatible_with(value_tensor.shape) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1161, in assert_is_compatible_with raise ValueError("Shapes %s and %s are incompatible" % (self, other)) ValueError: Shapes (768, 768) and (768, 12, 64) are incompatible`

I see. I just try it by myself and realized that transformers made some updates incompatible with the old versions. I will update the repo to fit the latest transformers soon. But temporarily, you could use "pip install transformers==4.3.2" and it should work. @lfoppiano @muthuku

**Comment by muthuku** [comment]
Thank you that worked! But is this warning anything of concern:
`WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss.`

**Comment by zhugeyicixin** [comment]
> Thank you that worked! But is this warning anything of concern:
> `WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss.`

No worries. That warning is OK. Gradients are not needed since training is already done.

**Comment by zhugeyicixin** [comment]
> > Hi I tried git lfs clone of the MatEntityRecognition which cloned the larger this larger file around 1.6 GB which I assume is the model, but I still got the same error. Did I do something wrong or is there something else I could try?:
> > `2021-06-24 17:12:45.242336: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations: AVX2 FMA To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags. lr_method_name, lr_method_parameters adamdecay {'lr': 1e-05, 'epsilon': 1e-08, 'warmup': 0.1} num_train_steps, num_warmup_steps 250000 25000 classifier_type lstm 2021-06-24 17:12:46.359474: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:176] None of the MLIR Optimization Passes are enabled (registered 2) WARNING:tensorflow:From /opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/array_ops.py:5049: calling gather (from tensorflow.python.ops.array_ops) with validate_indices is deprecated and will be removed in a future version. Instructions for updating: The `validate_indices` argument has no effect. Indices are always validated on CPU and never validated on GPU. WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss. WARNING:tensorflow:Gradients do not exist for variables ['ner_model/bert/pooler/dense/kernel:0', 'ner_model/bert/pooler/dense/bias:0'] when minimizing the loss. Traceback (most recent call last): File "<stdin>", line 1, in <module> File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/mat_models.py", line 641, in __init__ self.model = NERModel.reload_model(model_path=self.model_path, bert_path=self.bert_path) File "/Users/pragatimuthukumar/Documents/GitHub/MatEntityRecognition/materials_entity_recognition/scripts/model_framework.py", line 953, in reload_model model.load_weights(cp_path) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/training.py", line 2297, in load_weights status = self._trackable_saver.restore(filepath, options) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 1339, in restore checkpoint=checkpoint, proto_id=0).restore(self._graph_view.root) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 258, in restore restore_ops = trackable._restore_from_checkpoint_position(self) # pylint: disable=protected-access File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 972, in _restore_from_checkpoint_position visit_queue=visit_queue)) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 1007, in _single_restoration_from_checkpoint_position if child_position.bind_object(trackable=local_object): File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 312, in bind_object slot_name=slot_restoration.slot_name) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 1397, in _create_or_restore_slot_variable slot_variable_position.restore(slot_variable) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 258, in restore restore_ops = trackable._restore_from_checkpoint_position(self) # pylint: disable=protected-access File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 978, in _restore_from_checkpoint_position tensor_saveables, python_saveables)) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/tracking/util.py", line 309, in restore_saveables validated_saveables).restore(self.save_path_tensor, self.options) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 339, in restore restore_ops = restore_fn() File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 323, in restore_fn restore_ops.update(saver.restore(file_prefix, options)) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/functional_saver.py", line 116, in restore restored_tensors, restored_shapes=None) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/training/saving/saveable_object_util.py", line 132, in restore self.handle_op, self._var_shape, restored_tensor) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 308, in shape_safe_assign_variable_handle shape.assert_is_compatible_with(value_tensor.shape) File "/opt/anaconda3/lib/python3.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 1161, in assert_is_compatible_with raise ValueError("Shapes %s and %s are incompatible" % (self, other)) ValueError: Shapes (768, 768) and (768, 12, 64) are incompatible`
> 
> I see. I just try it by myself and realized that transformers made some updates incompatible with the old versions. I will update the repo to fit the latest transformers soon. But temporarily, you could use "pip install transformers==4.3.2" and it should work. @lfoppiano @muthuku

I just updated the model so it also works the latest transformers (4.11.3) now. @lfoppiano @muthuku
