### ISSUE TITLE
error while trying to run. please help me (urgent)

### ISSUE THREAD

**Issue by likhith-kumar-pampana** [CederGroupHub/MatEntityRecognition#29]
so i have able to install all the requirements for this correctly, but when i try to run this with a paragraph example it is giving me an error:
input_paras = "50 mg of SiO2 is taken and it is an inorganic compound"  #say for an example
from materials_entity_recognition import MatRecognition   
model = MatRecognition()  
result = model.mat_recognize(input_paras) 

then it throws an error:
File "c:\Users\likhi\anaconda3\envs\ceder\lib\site-packages\keras\optimizers\optimizer_experimental\optimizer.py", line 1151, in weight_decay_fn
      wd = tf.cast(self.weight_decay, variable.dtype)
Node: 'Cast_1'
Cast string to float is not supported
	 [[{{node Cast_1}}]] [Op:__inference_train_function_209896]

i actually am using your work in my masters research project and currently i don't know much about tensorflow,etc. So please look into this error and help me. Thanks for this amazing tool

**Comment by zhugeyicixin** [comment]
This issue likely stems from a version compatibility problem among different packages. I've updated the setup.py file, which should resolve the issue. If the problem persists, consider installing a specific version of transformers using the following command: pip install transformers==4.11.3. I have tested versions from 4.11.3 to 4.34.0 of transformers, and all have worked as expected.
